version: '3.8'

services:
    nginx:
        image: nginx:1.21.1
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./projectx:/var/www/
            # ----------------------------------------------------------
            # vendorとstorageを除かないと表示が異常に遅くなる
            # ----------------------------------------------------------
            # /var/www/storageと/var/www/vendorにデータをマウントしないための準備
            - storage-volumes:/var/www/storage
            - vendor-volumes:/var/www/vendor
            # ----------------------------------------------------------
        depends_on:
            - php

    php:
        build: ./docker/php
        volumes:
            - ./projectx:/var/www/
            # ----------------------------------------------------------
            # vendorとstorageを除かないと表示が異常に遅くなる
            # ----------------------------------------------------------
            # /var/www/storageと/var/www/vendorにデータをマウントしないための準備
            - storage-volumes:/var/www/storage
            - vendor-volumes:/var/www/vendor
            # ----------------------------------------------------------

    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: projectx
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=password
        depends_on:
            - mysql
        ports:
            - 8080:80

# ----------------------------------------------------------
# vendorとstorageを除かないと表示が異常に遅くなる
# ----------------------------------------------------------
# /var/www/storageと/var/www/vendorにデータをマウントしない設定
# フォルダは存在するがその中にデータはない状態となる
volumes:
    storage-volumes:
    vendor-volumes:
# ----------------------------------------------------------